<?php
/*
 * @file link_image.install
 * Contains install and update functions for Link Image Formatter module.
 */

/**
 * Implements hook_install().
 */
function link_image_install() {
  drupal_install_schema('link_image');
}

/**
 * Implements hook_uninstall().
 */
function link_image_uninstall() {
  drupal_uninstall_schema('link_image');
  db_query("DELETE FROM {variable} WHERE name LIKE 'link_image_%%'");
}
